runtime: nodejs20

instance_class: F2

env_variables: 
  BUCKET_NAME: "admin-panel-bucket"

handlers:
- url: /
  static_files: dist/admin-panel/browser/index.html
  upload: dist/admin-panel/browser/index.html

- url: /
  static_dir: dist/admin-panel